#!/bin/bash

function.declared ()
{
    local functions

    if [[ -n "$1" ]]
    then
        functions="$1"
    else
        functions=$(declare -F)
    fi

    functions=${functions//declare -f /}

    echo "$functions"
}

function.copy ()
{
    current_name="$1"
    new_name="$2"
    if [[ -n "$3" ]]
    then
        declare_context="$3"
    else
        declare_context=$(declare -f $current_name)
    fi
    eval "$(echo "$new_name()"; echo "$declare_context" | tail -n +2)"
}
