#!/bin/bash

# This is Bupler's init script.

if [[ -z "$BUPLER_LIB_PATH" ]]
then
    # During Bupler's setup we replace |BUPLER_LIB_PATH| with the actual path
    BUPLER_LIB_PATH="|BUPLER_LIB_PATH|" 
fi

bupler.type ()
{
    name="$1"

    type_function="$name"'.__type__'

    # The following exit status is 0 if $type_function isn't set
    if declare -f "$type_function" &> /dev/null
    then
        eval $1'.__type__'
        return 0
    fi
    echo 'unknown yet (soon to be develop)'

    return 0
}

bupler.import ()
{
    module="$1"

    if [[ "$(bupler.type "$module")" != 'Module' ]]
    then
        . $BUPLER_LIB_PATH"${module//./\/}"

        object.Object "$module"
    fi
}

# import the object module, which is required by bupler.import()
bupler.import object
