#!/bin/bash

# This is Bupler's init script.

if [[ -z "$BUPLER_LIB_PATH" ]]
then
    # During Bupler's setup we replace |BUPLER_LIB_PATH| with the actual path
    BUPLER_LIB_PATH="|BUPLER_LIB_PATH|" 
fi

bupler.import ()
{
    module="$1"

    . $BUPLER_LIB_PATH"${1//./\/}"
}
