#!/bin/bash

# This script loads the bupler.import function with which all bupler's modules
# can be load.

if [[ -z "$BUPLER_LIB_PATH" ]]
then
    # on the installation process we change |BUPLER_LIB_PATH|
    BUPLER_LIB_PATH="|BUPLER_LIB_PATH|" 
fi

bupler.import ()
{
    module="$1"

    . $BUPLER_LIB_PATH"${1//./\/}"
}
